---
- name: Create a catalog for backups
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'

- name: Create a backup script
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/mysql_backup.sh
    mode: '0755'

- name: Schedule MySQL backup
  cron:
    name: "MySQL backup"
    minute: "0"
    hour: "3"
    weekday: "1-5"
    job: "/usr/local/bin/mysql_backup.sh"
